### ISSUE TITLE
Missing start and load times lead to crash

### ISSUE THREAD

**Issue by nylen** [iarna/require-timer#1]
Error:

```
TypeError: Cannot read property '0' of undefined
    at timeSub (/media/250/code/node/money/node_modules/require-timer/index.js:20:20)
    at timingReport (/media/250/code/node/money/node_modules/require-timer/index.js:128:20)
    at process.results (/media/250/code/node/money/node_modules/require-timer/index.js:108:25)
    at process.emit (events.js:95:17)
    at process.exit (node.js:711:17)
    at Object.<anonymous> (/media/250/code/node/money/bin/banker.js:198:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Repro steps (I'm using node v0.10.29):

```
git clone https://github.com/nylen/node-banker.git
cd node-banker/
git checkout time-requires
npm install
npm install require-timer
bin/banker.js
```

This change works around the problem: https://github.com/nylen/require-timer/commit/workaround-missing-times

After that, rerunning `bin/banker.js` prints these two lines at the start of the `require-timer` output, then normal require times follow:

```
      NaN msec from start,       NaN msec to load: banker.js
      NaN msec from start,       NaN msec to load: banker.js
```

**Comment by iarna** [comment]
I'm a bit baffled as to how you could not have a start and end time. I mean, even with an entirely empty script I don't get that:

```
rebecca@sierra:require-timer$ [master] cat example.js
require("require-timer");
rebecca@sierra:require-timer$ [master] node example.js
    9.551 msec from start,     0.117 msec to load: example.js
    9.435 msec from start,     9.435 msec to load: example.js -> require-timer
    9.569 msec from start,     0.004 msec to load: async
```

Are you doing something unusual in banker.js? Oh, is one of its modules calling process.exit()?

**Comment by iarna** [comment]
I was able reproduce it with `process.exit()` in a required module. (As you can see it was fixed by the push above.)
